version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cryptolab}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cryptolab}
      POSTGRES_DB: ${POSTGRES_DB:-cryptolab}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-cryptolab}"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: ["bash", "-lc", "docker/wait-for-db.sh && docker/entrypoint.sh"]

volumes:
  pgdata:
